name = "my-app"
compatibility_date = "2024-04-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./dist"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
binding = "MY_KV"
id = "846db595ce064372bb2f2d73141fcc80"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "modi_d1-portfolio"
database_id = "344576d7-84c5-4eec-a0ad-ea5db09fccab"

# [ai]
# binding = "AI"